### ISSUE TITLE
oracle-oci build plugin fails with index out of range error on updating image capabilities

### ISSUE THREAD

**Issue by brailsmt** [hashicorp/packer-plugin-oracle#86]
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When building an OCI image the builder fails with an index out of range error on `schema.Items[0]` on line 227 in driver_oci.go.  The call on line 210 does not fail, and returns an empty list.  This is confirmed with the equivalent oci-cli call:
```
[20230222 15:48:19|user]$ oci compute image-capability-schema list --debug --image-id ocid1.image.oc1.iad.<id>
DEBUG:oci_cli.cli_metrics: 2023-02-22 21:48:28.062728: Metrics is not enabled
--- elided ---
INFO:oci.base_client.4498984848: 2023-02-22 21:48:28.068817: Request: GET https://iaas.us-ashburn-1.oraclecloud.com/[elided]/computeImageCapabilitySchemas
reply: 'HTTP/1.1 200 OK\r\n'
--- elided ---
header: Content-Length: 2
--- elided ---
```

The error was introduced in v1.0.3 with this commit:  https://github.com/hashicorp/packer-plugin-oracle/commit/b72475862307655c52c6610ce9e1862cdef411a1

#### Reproduction Steps

I'm unsure.  I'm building a custom image based on OEL7 using `packer build`

### Plugin and Packer version

From `packer version`
```
$ packer version
Packer v1.8.5
```
I am using v1.0.4 of the oracle-oci builder plugin:
```
$ ls ~/.packer.d/plugins/github.com/hashicorp/oracle/
packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64  packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64_SHA256SUM
```

### Simplified Packer Buildfile

I'm not sure this is relevant as I don't see anything in the documentation that would allow me to specify image capabilities when creating the image.

```json
{
  "builders": [
    {
      "type": "oracle-oci",
  ],
  "provisioners": [
    {
      "type": "chef-solo"
    }
}

```

### Operating system and Environment details

The image is OEL7.  I'm running `packer build` on a MacBook Pro (amd64_darwin)

### Log Fragments and crash.log files

```
Build 'oracle-oci' errored after 31 minutes 57 seconds: unexpected EOF

==> Wait completed after 31 minutes 57 seconds

==> Some builds didn't complete successfully and had errors:
--> oracle-oci: unexpected EOF

==> Builds finished but no artifacts were created.
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: panic: runtime error: index out of range [0] with length 0
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: goroutine 155 [running]:
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-oracle/builder/oci.(*driverOCI).UpdateImageCapabilitySchema(0xc0004f40f0, {0x2233f08, 0xc000546100}, {0xc00011d310, 0x50})
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       github.com/hashicorp/packer-plugin-oracle/builder/oci/driver_oci.go:227 +0x7d7
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-oracle/builder/oci.(*stepImage).Run(0xc000121fd0, {0x2233f08, 0xc000546100}, {0x22343a0, 0xc00072e510})
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       github.com/hashicorp/packer-plugin-oracle/builder/oci/step_image.go:46 +0x43a
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep/commonsteps.askStep.Run({{0x222c430?, 0xc000121fd0?}, {0x2235a68?, 0xc00072e0c0?}}, {0x2233f08, 0xc000546100}, {0x22343a0?, 0xc0007
2e510?})
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       github.com/hashicorp/packer-plugin-sdk@v0.3.2/multistep/commonsteps/multistep_runner.go:110 +0xb1
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc00072e5a0, {0x2233f08, 0xc000546100}, {0x22343a0, 0xc00072e510})
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       github.com/hashicorp/packer-plugin-sdk@v0.3.2/multistep/basic_runner.go:70 +0x2f3
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-oracle/builder/oci.(*Builder).Run(0xc000137800, {0x2233f08, 0xc000546100}, {0x2235a68?, 0xc00072e0c0}, {0x22245e0?, 0xc000614020})
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       github.com/hashicorp/packer-plugin-oracle/builder/oci/builder.go:85 +0x6a8
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc00011f5c0, 0x53e060?, 0xc00053e040)
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       github.com/hashicorp/packer-plugin-sdk@v0.3.2/rpc/builder.go:117 +0x1e3
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: reflect.Value.call({0xc000112900?, 0xc00011a338?, 0x13?}, {0x1fad5c3, 0x4}, {0xc000185ef8, 0x3, 0x3?})
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       reflect/value.go:556 +0x845
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: reflect.Value.Call({0xc000112900?, 0xc00011a338?, 0x3?}, {0xc0003fa6f8, 0x3, 0x3})
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       reflect/value.go:339 +0xbf
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: net/rpc.(*service).call(0xc00011f600, 0xc00010c150?, 0x0?, 0xc000120f40, 0xc000220f80, 0x1201305?, {0x1d55300?, 0xc00053e03c?, 0x1201286?}, {0x1d23300, ...}, ...)
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       net/rpc/server.go:381 +0x226
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin: created by net/rpc.(*Server).ServeCodec
2023/02/22 14:12:37 packer-plugin-oracle_v1.0.4_x5.0_darwin_amd64 plugin:       net/rpc/server.go:478 +0x3fe

```

**Comment by brailsmt** [comment]
Another thing to point out is that despite the log message saying that no artifacts where created, the image was successfully created and I can see it and launch it from the OCI console.

**Comment by eshneken** [comment]
@brailsmt What policies does the user who is running this have set?  Do you have, at minimum, the following policies set?

Allow group PackerGroup to manage instance-family in compartment ${COMPARTMENT_NAME}
Allow group PackerGroup to manage instance-images in compartment ${COMPARTMENT_NAME}
Allow group PackerGroup to use virtual-network-family in compartment ${COMPARTMENT_NAME}
Allow group PackerGroup to use compute-image-capability-schema in tenancy

@nywilken We added policy documentation but the links to that documentation doesn't seem to link correctly from this page:  https://github.com/hashicorp/packer-plugin-oracle/tree/main/docs.  Are you able to update?

**Comment by furkan-kalabalik** [comment]
any updates, or is it related to policies?

**Comment by eshneken** [comment]
I can't speak for the reporter, but I had no issue testing this.  I believe as long as the correct policies are in place there should be no issue.

**Comment by brailsmt** [comment]
It's been a year since I logged this and I can't recall our workaround or the steps to recreate the original issue.  Unfortunately, I can't confirm whether this was caused/solved by policies.

**Comment by furkan-kalabalik** [comment]
In `UpdateImageCapabilitySchema` function, there is an assumption about retrieved image capabilities. Without looking to size of returned items, there are operations to update schema but I've seen that some images(especially custom images) doesn't have that capabilities set and size of returned list is 0. After setting my base image capabilities, problem solved.

**Comment by eshneken** [comment]
Yes, I see it now and was able to replicate.  I've added a pull request to correct this issue.
